# =========================
#DEFAULT HOST / IP
# catch all unknown hosts & direct IP access
# =========================
server {
    listen 80 default_server;
    server_name _;

    return 301 https://tasktracker.md-consulting.dev$request_uri;
}


server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    return 301 https://tasktracker.md-consulting.dev$request_uri;
}


# =========================
# HTTPS server: task tracker
# =========================
server {
    listen 80;
    server_name tasktracker.md-consulting.dev;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name tasktracker.md-consulting.dev;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # -------------------------
    # API → Spring Boot
    # -------------------------
    location /api/ {
        proxy_pass http://backend:8080/api/;   # 🔥 QUAN TRỌNG: có dấu /

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # fix JWT header (optional nhưng nên có)
        proxy_set_header Authorization $http_authorization;
    }

    # -------------------------
    # Frontend → Angular (nginx container)
    # -------------------------
    location / {
        proxy_pass http://frontend:80;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
    }
}


# =========================
# CV Website HTTP
# =========================
server {
    listen 80;
    server_name cv.md-consulting.dev;

    return 301 https://$host$request_uri;
}

# =========================
# CV Website HTTPS
# =========================
server {
    listen 443 ssl;
    server_name cv.md-consulting.dev;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    root /usr/share/nginx/html/cv;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# =========================
# md-consulting.dev HTTP
# =========================
server {
    listen 80;
    server_name md-consulting.dev www.md-consulting.dev;

    return 301 https://cv.md-consulting.dev$request_uri;
}

# =========================
# md-consulting.dev HTTPS
# =========================
server {
    listen 443 ssl;
    server_name md-consulting.dev www.md-consulting.dev;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    return 301 https://cv.md-consulting.dev$request_uri;
}