--
-- PostgreSQL database dump
--

\restrict rVwpHfoUyzjwcFK91L0YD41RCOLn3jbUuTCRrZ5gRO8kHYM7Br13eoTT2k5a9Tx

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.activity (
    id bigint NOT NULL,
    action character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    username character varying(255)
);


ALTER TABLE public.activity OWNER TO "user";

--
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    message character varying(255),
    username character varying(255)
);


ALTER TABLE public.notification OWNER TO "user";

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.task (
    id bigint NOT NULL,
    assigned_to character varying(255),
    created_at timestamp(6) with time zone,
    description text,
    due_date timestamp(6) with time zone,
    priority character varying(255) NOT NULL,
    status character varying(255),
    title character varying(255),
    updated_at timestamp(6) with time zone,
    CONSTRAINT task_priority_check CHECK (((priority)::text = ANY (ARRAY[('LOW'::character varying)::text, ('MEDIUM'::character varying)::text, ('HIGH'::character varying)::text, ('CRITICAL'::character varying)::text]))),
    CONSTRAINT task_status_check CHECK (((status)::text = ANY (ARRAY[('TODO'::character varying)::text, ('IN_PROGRESS'::character varying)::text, ('DONE'::character varying)::text])))
);


ALTER TABLE public.task OWNER TO "user";

--
-- Name: task_comment; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.task_comment (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) with time zone,
    created_by character varying(255),
    created_by_full_name character varying(255),
    updated_at timestamp(6) with time zone,
    task_id bigint
);


ALTER TABLE public.task_comment OWNER TO "user";

--
-- Name: task_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.task_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_history; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.task_history (
    id bigint NOT NULL,
    changed_at timestamp(6) with time zone,
    changed_by character varying(255),
    changed_by_full_name character varying(255),
    field character varying(255),
    new_value character varying(255),
    old_value character varying(255),
    task_id bigint
);


ALTER TABLE public.task_history OWNER TO "user";

--
-- Name: task_history_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.task_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_tags; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.task_tags (
    task_id bigint NOT NULL,
    tag character varying(255)
);


ALTER TABLE public.task_tags OWNER TO "user";

--
-- Name: users; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    fullname character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text])))
);


ALTER TABLE public.users OWNER TO "user";

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: activity; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.activity (id, action, created_at, description, username) FROM stdin;
1	TASK_CREATE	2026-06-11 22:45:38.625968	Task 'Kafka Integration' was created.	admin
2	TASK_COMMENT	2026-06-11 22:45:57.809254	admin commented on Task #69	admin
3	TASK_UPDATED	2026-06-11 22:46:00.7093	Assignee was changed from NULL to admin	admin
4	TASK_UPDATED	2026-06-11 22:46:22.43629	Description was changed from  to Activity group\nNotification group	admin
\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.notification (id, created_at, is_read, message, username) FROM stdin;
1	2026-06-11 22:45:38.626025	f	Task 'Kafka Integration' created successfully	admin
\.


--
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.task (id, assigned_to, created_at, description, due_date, priority, status, title, updated_at) FROM stdin;
2	mngo	2026-04-20 09:02:20+00	Building a search bar component with Angular, including styling and autocomplete functionality	2026-04-28 09:02:25+00	CRITICAL	DONE	Build Frontend	2026-04-20 09:02:20+00
3	mngo	2026-04-20 09:00:25+00	Configure nginx and deploy the frontend and backend in a VPS	2026-04-21 09:00:25+00	HIGH	DONE	Deployment on VPS	2026-04-20 09:00:25+00
6	mngo	2026-04-19 09:00:25+00	Write Dockerfile and docker-compose files to enable deployment with one command	2026-04-19 09:00:25+00	MEDIUM	DONE	DevOps/Configuration	2026-04-19 09:00:25+00
9	user	2026-04-18 09:01:25+00	Backend: GET /tasks?page=0&size=10. Frontend: next / prev	2026-04-27 09:10:25+00	MEDIUM	DONE	Paginator	2026-04-18 09:01:25+00
11	lucas	2026-04-20 09:06:25+00	Practice Dink and drop 	2026-04-24 09:10:25+00	LOW	DONE	Play pickleball	2026-04-20 09:06:25+00
16	mia	2026-04-20 10:08:00+00	Parse filter and sort value in url and perform sorting & filtering at server side.	2026-04-28 07:10:25+00	HIGH	DONE	Deep sorting and filtering	2026-04-20 10:08:00+00
21	mngo	2026-04-21 14:09:00+00	Singleton Logger object with levels: log, info, debug, warn and error	\N	CRITICAL	DONE	Logger Service	2026-04-21 14:09:00+00
23	admin	2026-04-21 14:09:00+00	Show assigned to me tasks in dashboard	\N	CRITICAL	DONE	Assigned to Me	2026-04-21 14:09:00+00
24	mngo	2026-04-21 14:10:00+00	New Angular component for task details	\N	MEDIUM	DONE	Task Details component	2026-04-21 14:10:00+00
26	admin	2026-04-22 21:10:00+00	Top tags in dashboard	\N	CRITICAL	DONE	Top Tags	2026-04-22 21:10:00+00
33	admin	2026-04-25 10:10:00+00	New line chart in dashbaord for complete taks of last 7 days	2026-05-30 07:10:25+00	MEDIUM	DONE	Complete task chart	2026-04-25 10:10:00+00
36	admin	2026-04-27 13:00:22.55576+00	setup postgresql in windows and VPS	2026-04-26 22:00:00+00	CRITICAL	DONE	Postgresql setup	2026-04-27 13:00:25.094604+00
32	admin	2026-04-23 10:10:00+00	New Dialog to add a task. Autocomplete for tags	2026-04-27 02:00:00+00	CRITICAL	DONE	Add Task dialog	2026-04-28 14:30:56.609002+00
31	admin	2026-04-23 10:10:00+00	Show my work: due today, due in 7 days, and overdue	2026-05-30 07:10:25+00	HIGH	DONE	My work in dashboard	2026-04-27 13:02:20.151137+00
29	mngo	2026-04-23 06:10:00+00	by entering tag, the suggestion box mus tbe appeared	2026-05-01 07:10:25+00	HIGH	DONE	Tag autocomplete	2026-04-27 13:20:56.778032+00
30	admin	2026-04-23 10:10:00+00	Paginator for comment section and with load more buttons	2026-05-30 07:10:25+00	HIGH	DONE	Comment paginator	2026-04-27 13:21:52.355474+00
43	admin	2026-04-27 17:46:58.633236+00	Log full HTTP request + response	2026-04-28 22:00:00+00	CRITICAL	DONE	Log HTTP request + response	2026-05-04 08:41:20.757148+00
25	admin	2026-04-21 21:10:00+00	Each task can have multiple tags	2026-04-30 15:01:00+00	LOW	DONE	Tags feature	2026-04-27 15:01:43.49606+00
1	mngo	2026-04-20 09:02:25+00	 Implementing a REST API endpoint to retrieve user/task data in JSON format	2026-04-24 09:02:25+00	CRITICAL	DONE	Build Backend	2026-04-27 15:05:39.790161+00
20	admin	2026-04-21 00:09:00+00	Update frontend page Task list to use dropdown for assignee field	2026-04-28 07:10:25+00	MEDIUM	DONE	Task List - Assignee Dropdown	2026-04-27 14:22:41.52701+00
27	admin	2026-04-22 21:15:00+00	Task history feature for auditing	2026-04-27 07:10:00+00	LOW	DONE	Task Historiy	2026-04-27 15:06:28.122821+00
18	mngo	2026-04-20 22:07:00+00	Login function with Jwt	2026-04-27 07:10:25+00	HIGH	DONE	Login with Jwt	2026-04-27 15:06:38.250848+00
4	admin	2026-04-20 09:01:25+00	Dashboard with number of DONE/TODO/IN_PROGRESS and chart. Using chart.js	2026-04-21 09:01:25+00	HIGH	DONE	Dashboard	2026-04-27 18:37:20.747432+00
41	admin	2026-04-27 15:44:34.699529+00	New activiry feed view compinent\n	2026-04-27 17:00:00+00	CRITICAL	DONE	Activity feed	2026-04-28 01:59:11.709123+00
44	admin	2026-04-28 02:12:34.278544+00	Implement project across multiple taks.\nUser project role	2026-05-30 22:00:00+00	LOW	TODO	Project layer	2026-04-28 02:12:53.354942+00
40	admin	2026-04-27 15:40:05.85136+00		2026-04-29 17:00:00+00	LOW	DONE	Side menu with lougout button	2026-04-28 02:13:08.092367+00
5	admin	2026-04-20 07:00:25+00	Extend Task with Priority (Critial, high, medim, low) including backend and front end side.	2026-04-29 07:00:25+00	HIGH	DONE	Priority Function	2026-04-29 08:20:32.042568+00
42	admin	2026-04-27 16:02:56.269007+00	Log in json format.\nUnique id for each request	2026-04-29 17:00:00+00	HIGH	DONE	Structured logging with correlation id	2026-05-04 08:41:29.795526+00
39	admin	2026-04-27 13:46:57.251571+00	Extend search in tasks component with due date.\nDue date search is the first col.	2026-05-06 22:00:00+00	MEDIUM	DONE	Extend search with due date	2026-05-05 15:53:53.117795+00
45	\N	2026-04-28 15:48:54.733985+00		2026-05-01 16:13:00+00	LOW	DONE	Playwright test for Kanban board	2026-05-06 08:30:07.230161+00
37	admin	2026-04-27 13:01:42.558524+00	Update readme file with setup of Postgresql in VPS	2026-04-28 22:00:00+00	MEDIUM	DONE	Update readme file	2026-05-07 07:22:09.307754+00
34	admin	2026-04-27 12:59:02.111211+00	Integration and unit tests	2026-04-28 22:00:00+00	HIGH	DONE	Backend Testing	2026-05-07 07:22:17.625529+00
38	admin	2026-04-27 13:20:01.344338+00	With Selenium or Playwright	2026-05-29 22:00:00+00	LOW	DONE	E2E testing with Playwright	2026-05-08 08:46:08.643357+00
12	lucas	2026-04-20 08:00:25+00	Play tennis today. Practice forehand	2026-04-24 09:10:25+00	MEDIUM	DONE	Play Tennis	2026-05-12 08:47:51.395087+00
51	admin	2026-05-19 19:51:01.360475+00		2026-06-15 22:00:00+00	MEDIUM	DONE	Learn Kubernetes basics	2026-06-08 10:32:53.876598+00
10	mngo	2026-04-20 09:04:25+00	Add due date to task and highlight	2026-04-29 09:10:25+00	HIGH	DONE	Due Date and Overdue	2026-05-13 16:10:06.497726+00
46	admin	2026-05-07 08:11:11.41488+00		2026-06-03 17:56:00+00	LOW	IN_PROGRESS	Kafka for logging service	2026-05-19 17:57:07.25656+00
35	admin	2026-04-27 12:59:41.799221+00	Unit test: Vitest\nComponent test: Angular TestBed\nE2E / System test: Playwright	2026-05-30 15:00:00+00	HIGH	DONE	Frontend testing	2026-05-18 10:35:54.81274+00
47	admin	2026-05-07 08:12:11.052441+00	grant an user the access to the project.	2026-05-23 17:55:00+00	LOW	TODO	User-project role	2026-05-19 17:57:27.669009+00
13	admin	2026-04-20 06:00:25+00	If task is assigned. An email to assignee will be sent	2026-05-22 09:10:00+00	HIGH	TODO	Email notification	2026-05-19 17:56:16.807571+00
28	admin	2026-04-23 06:10:00+00	Task can have multiple attachments	2026-05-21 07:10:00+00	HIGH	IN_PROGRESS	File Upload	2026-05-19 17:56:46.09402+00
22	admin	2026-04-21 14:09:00+00	Extend logger service with context. The context can be set from other services	\N	CRITICAL	DONE	Logger Service Context	2026-05-19 17:57:47.553958+00
52	admin	2026-05-19 19:51:52.43578+00		2026-05-26 22:00:00+00	HIGH	TODO	Deploy app on K8s 	2026-05-19 21:51:22.931936+00
48	mngo	2026-05-12 08:48:10.64632+00		2026-05-14 22:00:00+00	LOW	DONE	Prickleball traning	2026-06-08 10:15:43.435405+00
15	admin	2026-04-20 09:02:50+00	Implement feature "Task comments"	2026-05-01 07:10:25+00	LOW	DONE	Task Comments	2026-05-21 10:29:35.856519+00
19	mngo	2026-04-20 23:08:00+00	New API to fetch all assignee list from database	2026-05-30 07:10:25+00	CRITICAL	DONE	Option/ Assignee List api	2026-05-22 08:20:29.904818+00
17	mngo	2026-04-20 22:07:00+00	Extend JWT authentication with refresh token. Frontend: auto renew new token 5 minute before expiration	2026-04-22 07:10:25+00	HIGH	DONE	Refresh token	2026-05-22 08:20:36.091719+00
14	admin	2026-04-19 09:09:25+00	TODO → IN_PROGRESS → DONE. Angular CDK Dragdrop	2026-04-30 07:10:25+00	CRITICAL	DONE	Kanban Drag & Drop Feature	2026-05-22 12:17:23.913073+00
50	admin	2026-05-14 10:39:22.500311+00		2026-05-30 22:00:00+00	CRITICAL	DONE	Prepare interview‘s questions	2026-05-24 08:50:26.084663+00
49	admin	2026-05-12 08:48:34.207645+00		2026-05-30 22:00:00+00	LOW	DONE	Pickleball tounier	2026-05-26 08:12:51.527434+00
8	admin	2026-04-20 09:10:25+00	Implement and integrate ODIC authentication with Keycloak	2026-04-25 09:10:25+00	MEDIUM	IN_PROGRESS	Integrate Keycloak	2026-05-26 10:25:04.45733+00
7	mngo	2026-04-20 09:05:25+00	Modifying a database schema by adding a deleted_at column for soft-delete functionality	2026-04-22 09:05:25+00	HIGH	DONE	Database Management	2026-05-19 21:51:35.670164+00
53	admin	2026-05-21 10:33:42.056545+00	Teilnahme an Pitch Club Developer Edition in Dortmund	2026-05-20 22:00:00+00	CRITICAL	DONE	Pitch Club Developer Edition	2026-05-22 12:22:16.144561+00
56	admin	2026-05-26 08:09:44.738735+00		\N	HIGH	TODO	Prepare interview question regarding Java	2026-05-26 08:09:44.738736+00
58	admin	2026-05-26 08:14:54.670016+00		2026-05-30 22:00:00+00	CRITICAL	DONE	Write docker compose for the Mini Jira Project	2026-05-26 11:45:24.636435+00
54	admin	2026-05-22 12:16:24.817525+00	Until 31.05.2026	2026-05-30 22:00:00+00	MEDIUM	DONE	Learn English 15 minutes everyday	2026-05-29 05:09:37.555092+00
55	admin	2026-05-22 12:16:58.821345+00	Until 31.05.2026	2026-05-30 22:00:00+00	HIGH	DONE	Lean German 15 minutes everyday	2026-05-29 05:09:42.105492+00
60	admin	2026-05-29 08:30:37.2173+00	After AWS Solution Architect Associate	\N	MEDIUM	TODO	Complete: Certified Kubernetes Application Developer	2026-05-29 08:30:37.217301+00
57	admin	2026-05-26 08:12:40.653915+00		2026-05-30 22:00:00+00	HIGH	DONE	OpenAPI vs Swagger	2026-06-03 11:13:50.170894+00
59	admin	2026-05-29 08:28:34.008757+00		2026-06-13 08:28:00+00	HIGH	IN_PROGRESS	Complete Certification: AWS Solutions Architect Associate	2026-06-03 11:13:59.496003+00
63	admin	2026-06-08 10:13:12.099946+00		2026-06-17 22:00:00+00	LOW	TODO	AWS - SAA - Timed Mode 2	2026-06-08 10:13:12.099947+00
62	admin	2026-06-08 10:13:03.437044+00		2026-06-17 22:00:00+00	CRITICAL	TODO	AWS - SAA - Timed Mode 1	2026-06-08 10:13:36.008555+00
64	admin	2026-06-08 10:14:01.257471+00		2026-06-17 22:00:00+00	LOW	IN_PROGRESS	AWS - SAA - Timed Mode 3	2026-06-08 10:14:04.965128+00
61	admin	2026-06-03 11:17:06.472374+00	- allgemeine Fragen inklusiv Selbstverstellung\n- Backend-Fragen\n- Frontend-Fragen\n\n	2026-06-02 22:00:00+00	CRITICAL	DONE	Vorbereitung für Interview	2026-06-08 10:15:36.278103+00
65	admin	2026-06-08 10:15:07.964941+00	- complete the AWS - SAA - C03 certificate	2026-06-09 22:00:00+00	CRITICAL	IN_PROGRESS	SAA-C03 - AWS Certified Solutions Architect - Associate - English (ENU)	2026-06-08 10:32:12.042292+00
66	admin	2026-06-10 12:37:56.551894+00		2026-06-18 22:00:00+00	HIGH	TODO	AWS - host the app into Aws	2026-06-10 12:39:19.703759+00
69	admin	2026-06-11 22:45:38.402774+00	Activity group\nNotification group	\N	LOW	TODO	Kafka Integration	2026-06-11 22:46:22.43243+00
\.


--
-- Data for Name: task_comment; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.task_comment (id, content, created_at, created_by, created_by_full_name, updated_at, task_id) FROM stdin;
1	Nice feature, very useful for searching!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	25
2	Maybe we should have search fucntion by multiple tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	25
3	UI looks greate 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	25
4	Nice feature, very useful for searching!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	25
5	Maybe we should have search fucntion by multiple tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	25
6	UI looks greate 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	25
7	Nice feature, very useful for searching!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	26
8	Maybe we should have search fucntion by multiple tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	26
9	UI looks greate 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	26
10	Nice feature, very useful for analytics!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	26
11	Maybe we should add pagination for tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	26
12	UI looks clean 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	26
13	Nice feature, very useful for searching!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	27
14	Maybe we should have search fucntion by multiple tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	27
15	UI looks greate 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	27
16	Nice feature, very useful for searching!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	28
17	Maybe we should have search fucntion by multiple tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	28
18	UI looks greate 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	28
19	Nice feature, very useful for searching!	2026-04-22 21:15:00+00	admin	Admin	2026-04-22 21:15:00+00	29
20	Maybe we should have search fucntion by multiple tags?	2026-04-22 21:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	29
21	UI looks greate 👍	2026-04-22 21:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	29
22	Nice feature, very useful for searching!	2026-04-23 10:15:00+00	admin	Admin	2026-04-22 21:15:00+00	30
23	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	30
24	UI looks greate 👍	2026-04-23 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	30
25	Lets have a meeting to discuss!	2026-04-23 10:30:00+00	admin	Admin	2026-04-22 21:15:00+00	30
26	Arrange a meeting tomowrrow	2026-04-23 10:35:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	30
27	UI looks greate 👍	2026-04-23 10:36:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	30
28	Nice feature, very useful for searching!	2026-04-23 10:37:00+00	admin	Admin	2026-04-22 21:15:00+00	30
29	When does it get done?	2026-04-23 10:38:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	30
30	I like this 👍	2026-04-23 10:39:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	30
31	UI could be improved	2026-04-23 10:40:00+00	admin	Admin	2026-04-22 21:15:00+00	30
32	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:41:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	30
33	UI looks greate 👍	2026-04-23 10:42:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	30
34	Nice feature, very useful for searching!	2026-04-23 10:43:00+00	admin	Admin	2026-04-22 21:15:00+00	30
35	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:44:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	30
36	UI looks greate 👍	2026-04-23 10:45:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	30
37	Nice feature, very useful for searching!	2026-04-23 10:46:00+00	admin	Admin	2026-04-22 21:15:00+00	30
38	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	30
39	Amzing work 👍	2026-04-23 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	30
40	Nice feature, very useful for searching!	2026-04-23 10:15:00+00	admin	Admin	2026-04-22 21:15:00+00	31
41	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	31
42	UI looks greate 👍	2026-04-23 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	31
43	Lets have a meeting to discuss!	2026-04-23 10:30:00+00	admin	Admin	2026-04-22 21:15:00+00	31
44	Arrange a meeting tomowrrow	2026-04-23 10:35:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	31
45	UI looks greate 👍	2026-04-23 10:36:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	31
46	Nice feature, very useful for searching!	2026-04-23 10:37:00+00	admin	Admin	2026-04-22 21:15:00+00	31
47	When does it get done?	2026-04-23 10:38:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	31
48	I like this 👍	2026-04-23 10:39:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	31
49	UI could be improved	2026-04-23 10:40:00+00	admin	Admin	2026-04-22 21:15:00+00	31
50	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:41:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	31
51	UI looks greate 👍	2026-04-23 10:42:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	31
52	Nice feature, very useful for searching!	2026-04-23 10:43:00+00	admin	Admin	2026-04-22 21:15:00+00	31
53	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:44:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	31
54	UI looks greate 👍	2026-04-23 10:45:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	31
55	Nice feature, very useful for searching!	2026-04-23 10:46:00+00	admin	Admin	2026-04-22 21:15:00+00	31
56	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	31
57	Amzing work 👍	2026-04-23 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	31
58	Nice feature, very useful for searching!	2026-04-23 10:15:00+00	admin	Admin	2026-04-22 21:15:00+00	32
59	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	32
60	UI looks greate 👍	2026-04-23 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	32
61	Lets have a meeting to discuss!	2026-04-23 10:30:00+00	admin	Admin	2026-04-22 21:15:00+00	32
62	Arrange a meeting tomowrrow	2026-04-23 10:35:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	32
63	UI looks greate 👍	2026-04-23 10:36:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	32
64	Nice feature, very useful for searching!	2026-04-23 10:37:00+00	admin	Admin	2026-04-22 21:15:00+00	32
65	When does it get done?	2026-04-23 10:38:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	32
66	Nice feature, very useful for searching!	2026-04-23 10:46:00+00	admin	Admin	2026-04-22 21:15:00+00	32
67	Maybe we should have search fucntion by multiple tags?	2026-04-23 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	32
68	Amzing work 👍	2026-04-23 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	32
69	Nice feature, very useful for searching!	2026-04-25 10:15:00+00	admin	Admin	2026-04-22 21:15:00+00	33
70	Maybe we should have search fucntion by multiple tags?	2026-04-25 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	33
71	UI looks greate 👍	2026-04-25 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	33
72	Lets have a meeting to discuss!	2026-04-25 10:30:00+00	admin	Admin	2026-04-22 21:15:00+00	33
73	Arrange a meeting tomowrrow	2026-04-25 10:35:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	33
74	UI looks greate 👍	2026-04-25 10:36:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	33
75	Nice feature, very useful for searching!	2026-04-25 10:37:00+00	admin	Admin	2026-04-22 21:15:00+00	33
76	When does it get done?	2026-04-25 10:38:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	33
77	I like this 👍	2026-04-25 10:39:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	33
78	UI could be improved	2026-04-25 10:40:00+00	admin	Admin	2026-04-22 21:15:00+00	33
79	Maybe we should have search fucntion by multiple tags?	2026-04-25 10:41:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	33
80	UI looks greate 👍	2026-04-25 10:42:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	33
81	Nice feature, very useful for searching!	2026-04-25 10:43:00+00	admin	Admin	2026-04-22 21:15:00+00	33
82	Maybe we should have search fucntion by multiple tags?	2026-04-25 10:44:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	33
83	UI looks greate 👍	2026-04-25 10:45:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	33
84	Nice feature, very useful for searching!	2026-04-25 10:46:00+00	admin	Admin	2026-04-22 21:15:00+00	33
85	Maybe we should have search fucntion by multiple tags?	2026-04-25 10:20:00+00	mngo	Minh Ngo	2026-04-22 21:20:00+00	33
86	Amzing work 👍	2026-04-25 10:25:00+00	lucas	Lucas Ngo	2026-04-22 21:25:00+00	33
87	<p>update&nbsp;doncumentation</p>	2026-04-27 13:01:51.287196+00	admin	Admin	2026-04-27 13:01:51.287198+00	37
88	<p>due&nbsp;date&nbsp;options:&nbsp;overdue,&nbsp;due&nbsp;today,&nbsp;due&nbsp;this&nbsp;week,&nbsp;later</p>	2026-04-27 13:47:22.2087+00	admin	Admin	2026-04-27 13:47:22.2087+00	39
89	<p>New&nbsp;comment</p>	2026-04-27 14:22:53.162985+00	admin	Admin	2026-04-27 14:22:53.162985+00	20
90	<p><strong>Using</strong>&nbsp;richtext&nbsp;for&nbsp;comment.</p><p>Link&nbsp;to&nbsp;github:&nbsp;<a href="https://github.com/minhducngo85/TaskTracker" rel="noopener noreferrer" target="_blank">https://github.com/minhducngo85/TaskTracker</a></p>	2026-04-27 14:23:33.038313+00	admin	Admin	2026-04-27 14:23:33.038313+00	20
91	<p>Should&nbsp;have&nbsp;paginator</p>	2026-04-27 15:36:44.696949+00	admin	Admin	2026-04-27 15:36:44.69695+00	15
92	<p>Logout&nbsp;btn&nbsp;is&nbsp;at&nbsp;left&nbsp;bottom</p>	2026-04-27 15:40:39.049718+00	admin	Admin	2026-04-27 15:40:39.049719+00	40
93	<p>This&nbsp;can&nbsp;be&nbsp;included&nbsp;in&nbsp;dashboard&nbsp;and&nbsp;my&nbsp;work&nbsp;component</p>	2026-04-27 15:45:44.342948+00	admin	Admin	2026-04-27 15:45:44.342948+00	41
94	<p>&lt;pattern&gt;</p><p></p><p>&nbsp;&nbsp;%d{yyyy-MM-dd&nbsp;HH:mm:ss}&nbsp;[%level]&nbsp;[%X{correlationId}]&nbsp;%msg%n</p><p></p><p>&lt;/pattern&gt;</p><p></p>	2026-04-27 16:19:21.511665+00	admin	Admin	2026-04-27 16:19:21.511665+00	42
95	<p><span style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">{&nbsp;&quot;message&quot;:&nbsp;&quot;Create&nbsp;task&quot;,&nbsp;&quot;requestId&quot;:&nbsp;&quot;123-abc&quot;&nbsp;}</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">{&nbsp;&quot;message&quot;:&nbsp;&quot;Save&nbsp;DB&quot;,&nbsp;&quot;requestId&quot;:&nbsp;&quot;123-abc&quot;&nbsp;}</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">{&nbsp;&quot;message&quot;:&nbsp;&quot;Send&nbsp;notification&quot;,&nbsp;&quot;requestId&quot;:&nbsp;&quot;123-abc&quot;&nbsp;}</span></p><p></p>	2026-04-27 17:07:47.19222+00	admin	Admin	2026-04-27 17:07:47.192221+00	42
96	<p>using:&nbsp;logstash-logback-encoder</p><p></p>	2026-04-27 17:11:11.790411+00	admin	Admin	2026-04-27 17:11:11.790411+00	42
97	<p>[INFO]&nbsp;[abc-123]&nbsp;REQUEST&nbsp;POST&nbsp;/api/tasks&nbsp;body={&quot;title&quot;:&quot;Task&nbsp;A&quot;}</p><p>[INFO]&nbsp;[abc-123]&nbsp;RESPONSE&nbsp;201&nbsp;/api/tasks&nbsp;time=120ms&nbsp;body={&quot;id&quot;:1,&quot;title&quot;:&quot;Task&nbsp;A&quot;}</p>	2026-04-27 17:47:08.545897+00	admin	Admin	2026-04-27 17:47:08.545897+00	43
98	<p>implement&nbsp;the&nbsp;log&nbsp;message&nbsp;like&nbsp;example&nbsp;below.</p>	2026-04-27 17:55:04.998355+00	admin	Admin	2026-04-27 17:55:04.998356+00	43
99	<p>Integration&nbsp;tests&nbsp;for&nbsp;controller</p>	2026-04-28 15:09:30.387648+00	admin	Admin	2026-04-28 15:09:30.387648+00	34
100	<ul><li><span style="color: rgb(31, 35, 40);">Unit&nbsp;tests&nbsp;for&nbsp;service&nbsp;layer&nbsp;(business&nbsp;logic&nbsp;validation)</span></li></ul><p></p>	2026-04-28 15:10:39.303343+00	admin	Admin	2026-04-28 15:10:39.303343+00	34
101	<ul><li><span style="color: rgb(31, 35, 40);">Unit&nbsp;test:&nbsp;Vitest</span></li><li><span style="color: rgb(31, 35, 40);">Component&nbsp;test:&nbsp;Angular&nbsp;TestBed</span></li><li><span style="color: rgb(31, 35, 40);">E2E&nbsp;/&nbsp;System&nbsp;test:&nbsp;Playwright</span></li></ul><p></p>	2026-04-28 15:12:50.539638+00	admin	Admin	2026-04-28 15:12:50.539639+00	35
102	"<p>17:00:&nbsp;Einlass</p><p>17:30&nbsp;-&nbsp;18:30&nbsp;Ptches&nbsp;der&nbsp;Firmen&nbsp;inkl.&nbsp;Q&amp;A</p>"	2026-05-21 10:34:28.197584+00	admin	Admin	2026-05-21 10:34:28.197585+00	53
103	"<p>Brandschachtstraße&nbsp;14,&nbsp;Dortmund</p>"	2026-05-21 10:34:54.055885+00	admin	Admin	2026-05-21 10:34:54.055885+00	53
104	<p>Runde:</p><p>ab&nbsp;18:30:&nbsp;Fingerfood&nbsp;&amp;&nbsp;Drinks</p>	2026-05-21 10:45:04.319922+00	admin	Admin	2026-05-21 10:45:04.319924+00	53
105	<p><strong>AWS&nbsp;Solutions&nbsp;Architect&nbsp;Associate&nbsp;(SAA-C03)</strong>.</p>	2026-05-29 08:29:27.759948+00	admin	Admin	2026-05-29 08:29:27.759948+00	59
106	<p>Complete&nbsp;the&nbsp;certificate&nbsp;after&nbsp;the&nbsp;<span style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);">AWS&nbsp;Solution&nbsp;Architect&nbsp;Associate</span></p>	2026-05-29 08:31:07.332855+00	admin	Admin	2026-05-29 08:31:07.332856+00	60
107	<p>Die&nbsp;Prüfung&nbsp;is&nbsp;bereit&nbsp;für&nbsp;nächste&nbsp;Woche&nbsp;geplant.</p>	2026-06-03 11:14:36.113902+00	admin	Admin	2026-06-03 11:14:36.113902+00	59
108	<p>The&nbsp;exam&nbsp;is&nbsp;on&nbsp;08.06.2024</p>	2026-06-08 10:15:23.712141+00	admin	Admin	2026-06-08 10:15:23.712141+00	65
109	<p>create&nbsp;activity-group</p><p></p>	2026-06-11 22:45:57.79281+00	admin	Admin	2026-06-11 22:45:57.792813+00	69
\.


--
-- Data for Name: task_history; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.task_history (id, changed_at, changed_by, changed_by_full_name, field, new_value, old_value, task_id) FROM stdin;
1	2026-04-23 18:37:00+00	admin	Admin	status	IN_PROGRESS	TODO	30
2	2026-04-23 18:37:30+00	admin	Admin	status	DONE	IN_PROGRESS	30
3	2026-04-23 18:38:00+00	admin	Admin	status	IN_PROGRESS	DONE	30
4	2026-04-23 18:38:30+00	mngo	Minh Ngo	status	TODO	IN_PROGRESS	30
5	2026-04-23 18:39:00+00	admin	Admin	status	IN_PROGRESS	TODO	30
6	2026-04-23 18:38:10+00	admin	Admin	priority	MEDIUM	HIGH	30
7	2026-04-23 18:38:20+00	mngo	Minh Ngo	priority	HIGH	MEDIUM	30
8	2026-04-23 18:21:00+00	admin	Admin	description	Paginator for comment section and with load more buttons 2	Paginator for comment section and with load more buttons	30
9	2026-04-23 18:06:00+00	mngo	Minh Ngo	tags	paginator,comment,frontend,today	paginator,comment,frontend	30
10	2026-04-23 18:37:00+00	admin	Admin	status	IN_PROGRESS	TODO	31
11	2026-04-23 18:37:30+00	admin	Admin	status	DONE	IN_PROGRESS	31
12	2026-04-23 18:38:00+00	admin	Admin	status	IN_PROGRESS	DONE	31
13	2026-04-23 18:38:30+00	mngo	Minh Ngo	status	TODO	IN_PROGRESS	31
14	2026-04-23 18:39:00+00	admin	Admin	status	IN_PROGRESS	TODO	31
15	2026-04-23 18:38:10+00	admin	Admin	priority	MEDIUM	HIGH	31
16	2026-04-23 18:38:20+00	mngo	Minh Ngo	priority	HIGH	MEDIUM	31
17	2026-04-23 18:21:00+00	admin	Admin	description	Paginator for comment section and with load more buttons 2	Paginator for comment section and with load more buttons	31
18	2026-04-23 18:37:00+00	admin	Admin	status	IN_PROGRESS	TODO	32
19	2026-04-23 18:37:30+00	admin	Admin	status	DONE	IN_PROGRESS	32
20	2026-04-23 18:38:00+00	admin	Admin	status	IN_PROGRESS	DONE	32
21	2026-04-23 18:38:30+00	mngo	Minh Ngo	status	TODO	IN_PROGRESS	32
22	2026-04-24 18:39:00+00	admin	Admin	status	IN_PROGRESS	TODO	32
23	2026-04-25 11:10:00+00	admin	Admin	task	task created	null	33
24	2026-04-27 12:59:02.141477+00	admin	Admin	task	Task created	Null	34
25	2026-04-27 12:59:41.8037+00	admin	Admin	task	Task created	Null	35
26	2026-04-27 13:00:22.560211+00	admin	Admin	task	Task created	Null	36
27	2026-04-27 13:00:25.089037+00	admin	Admin	status	DONE	TODO	36
28	2026-04-27 13:00:38.707666+00	admin	Admin	status	IN_PROGRESS	TODO	32
29	2026-04-27 13:01:42.563455+00	admin	Admin	task	Task created	Null	37
30	2026-04-27 13:01:56.715514+00	admin	Admin	priority	MEDIUM	LOW	37
31	2026-04-27 13:02:20.14844+00	admin	Admin	status	DONE	TODO	31
32	2026-04-27 13:11:34.055498+00	admin	Admin	status	IN_PROGRESS	TODO	34
33	2026-04-27 13:20:01.347743+00	admin	Admin	task	Task created	Null	38
34	2026-04-27 13:20:56.77566+00	admin	Admin	status	DONE	TODO	29
35	2026-04-27 13:21:14.93237+00	admin	Admin	tags	paginator,comment,frontend,backend	paginator,comment,frontend	30
36	2026-04-27 13:21:52.353361+00	admin	Admin	status	DONE	TODO	30
37	2026-04-27 13:46:57.255302+00	admin	Admin	task	Task created	Null	39
38	2026-04-27 13:47:30.45325+00	admin	Admin	tags	search,backend	search	39
39	2026-04-27 13:48:07.753092+00	admin	Admin	description	- extend search in tasks component with due date  	- extend search in tasks component with due date 	39
40	2026-04-27 13:48:28.360522+00	admin	Admin	tags	search,backend,api	search,backend	39
41	2026-04-27 14:22:41.524409+00	admin	Admin	status	DONE	TODO	20
42	2026-04-27 14:26:36.194281+00	admin	Admin	description	Extend search in tasks component with due date.\nDue date search is the first col.	- extend search in tasks component with due date  	39
43	2026-04-27 14:51:57.321495+00	admin	Admin	dueDate	null	2026-05-01T07:10:25Z	27
44	2026-04-27 14:52:01.339199+00	admin	Admin	dueDate	2026-04-27T07:10:00Z	null	27
45	2026-04-27 14:59:57.111545+00	admin	Admin	tags	search,backend,api,angular material	search,backend,api	39
46	2026-04-27 15:00:47.749485+00	admin	Admin	dueDate	2026-04-27T15:00:00Z	null	35
47	2026-04-27 15:00:50.271926+00	admin	Admin	dueDate	2026-05-30T15:00:00Z	2026-04-27T15:00:00Z	35
48	2026-04-27 15:01:15.560184+00	admin	Admin	dueDate	2026-04-27T15:01:00Z	null	25
49	2026-04-27 15:01:16.875284+00	admin	Admin	dueDate	2026-04-30T15:01:00Z	2026-04-27T15:01:00Z	25
50	2026-04-27 15:01:43.494143+00	admin	Admin	status	DONE	TODO	25
51	2026-04-27 15:05:39.788569+00	admin	Admin	status	DONE	IN_PROGRESS	1
52	2026-04-27 15:06:28.121078+00	admin	Admin	status	DONE	TODO	27
53	2026-04-27 15:06:38.249231+00	admin	Admin	status	DONE	TODO	18
54	2026-04-27 15:11:09.53415+00	admin	Admin	status	IN_PROGRESS	TODO	15
55	2026-04-27 15:11:14.032759+00	admin	Admin	assignedTo	admin	lucas	15
56	2026-04-27 15:15:16.435593+00	admin	Admin	status	IN_PROGRESS	TODO	5
57	2026-04-27 15:15:19.462317+00	admin	Admin	assignedTo	admin	lucas	5
58	2026-04-27 15:37:33.432753+00	admin	Admin	tags	postgresql,database,linux	postgresql,database	7
59	2026-04-27 15:40:05.854364+00	admin	Admin	task	Task created	Null	40
60	2026-04-27 15:43:00.754057+00	admin	Admin	tags	testing,selenium	testing	38
61	2026-04-27 15:44:34.702507+00	admin	Admin	task	Task created	Null	41
62	2026-04-27 15:46:16.044542+00	admin	Admin	status	IN_PROGRESS	TODO	41
63	2026-04-27 16:02:56.27371+00	admin	Admin	task	Task created	Null	42
64	2026-04-27 16:03:06.274701+00	admin	Admin	tags	backend,logger	backend	42
65	2026-04-27 17:46:58.635432+00	admin	Admin	task	Task created	Null	43
66	2026-04-27 18:37:20.74567+00	admin	Admin	status	DONE	TODO	4
67	2026-04-28 01:59:11.707024+00	admin	Admin	status	DONE	IN_PROGRESS	41
68	2026-04-28 01:59:33.338042+00	admin	Admin	dueDate	2026-05-29T07:10:00Z	2026-05-30T07:10:25Z	32
69	2026-04-28 01:59:36.576023+00	admin	Admin	dueDate	2026-05-27T07:10:00Z	2026-05-29T07:10:00Z	32
70	2026-04-28 02:00:22.478421+00	admin	Admin	dueDate	null	2026-05-27T07:10:00Z	32
71	2026-04-28 02:00:25.782561+00	admin	Admin	dueDate	2026-03-28T03:00:00Z	null	32
72	2026-04-28 02:00:26.966079+00	admin	Admin	dueDate	2026-04-28T02:00:00Z	2026-03-28T03:00:00Z	32
73	2026-04-28 02:00:28.185079+00	admin	Admin	dueDate	2026-04-27T02:00:00Z	2026-04-28T02:00:00Z	32
74	2026-04-28 02:12:34.281739+00	admin	Admin	task	Task created	Null	44
75	2026-04-28 02:12:53.353628+00	admin	Admin	tags	backend,database,api		44
76	2026-04-28 02:13:08.090893+00	admin	Admin	status	DONE	TODO	40
77	2026-04-28 10:54:45.850128+00	admin	Admin	priority	CRITICAL	HIGH	32
78	2026-04-28 14:28:10.602593+00	admin	Admin	title	E2E testing with Playwright	Automation testing	38
79	2026-04-28 14:30:56.607164+00	admin	Admin	status	DONE	IN_PROGRESS	32
80	2026-04-28 15:13:03.054792+00	admin	Admin	description	Unit test: Vitest\nComponent test: Angular TestBed\nE2E / System test: Playwright	Unit tests with vitest	35
81	2026-04-28 15:48:54.767145+00	admin	Admin	task	Task created	Null	45
82	2026-04-28 15:48:57.536439+00	admin	Admin	status	IN_PROGRESS	TODO	45
83	2026-04-28 15:49:12.693703+00	admin	Admin	tags	testing,frontend		45
84	2026-04-28 16:13:17.258572+00	admin	Admin	dueDate	2026-04-28T16:13:00Z	null	45
85	2026-04-28 16:13:19.53244+00	admin	Admin	dueDate	2026-04-30T16:13:00Z	2026-04-28T16:13:00Z	45
86	2026-04-28 16:14:36.752187+00	admin	Admin	dueDate	2026-05-01T16:13:00Z	2026-04-30T16:13:00Z	45
87	2026-04-29 08:20:32.039478+00	admin	Admin	status	DONE	IN_PROGRESS	5
88	2026-05-04 08:41:20.754667+00	admin	Admin	status	DONE	TODO	43
89	2026-05-04 08:41:29.79323+00	admin	Admin	status	DONE	TODO	42
90	2026-05-05 15:53:53.093151+00	admin	Admin	status	DONE	TODO	39
91	2026-05-06 08:30:07.202616+00	admin	Admin	status	DONE	IN_PROGRESS	45
92	2026-05-07 07:22:09.305414+00	admin	Admin	status	DONE	TODO	37
93	2026-05-07 07:22:17.622528+00	admin	Admin	status	DONE	IN_PROGRESS	34
94	2026-05-07 08:11:11.419456+00	admin	Admin	task	Task created	Null	46
95	2026-05-07 08:12:11.055908+00	admin	Admin	task	Task created	Null	47
96	2026-05-08 08:46:08.640877+00	admin	Admin	status	DONE	TODO	38
97	2026-05-12 08:47:51.392916+00	admin	Admin	status	DONE	TODO	12
98	2026-05-12 08:48:10.649229+00	admin	Admin	task	Task created	Null	48
99	2026-05-12 08:48:34.209819+00	admin	Admin	task	Task created	Null	49
100	2026-05-12 11:43:51.544585+00	admin	Admin	status	IN_PROGRESS	TODO	48
101	2026-05-13 16:10:06.495635+00	admin	Admin	status	DONE	IN_PROGRESS	10
102	2026-05-14 10:39:22.502703+00	admin	Admin	task	Task created	Null	50
103	2026-05-18 10:35:49.870254+00	admin	Admin	status	IN_PROGRESS	TODO	46
104	2026-05-18 10:35:54.811057+00	admin	Admin	status	DONE	TODO	35
105	2026-05-19 17:55:23.845546+00	admin	Admin	dueDate	2026-05-23T17:55:00Z	null	47
106	2026-05-19 17:56:08.355551+00	admin	Admin	assignedTo	admin	lucas	13
107	2026-05-19 17:56:16.805875+00	admin	Admin	dueDate	2026-05-22T09:10:00Z	2026-04-22T09:10:25Z	13
108	2026-05-19 17:56:35.281216+00	admin	Admin	assignedTo	admin	mngo	28
109	2026-05-19 17:56:46.092615+00	admin	Admin	dueDate	2026-05-21T07:10:00Z	2026-05-02T07:10:25Z	28
110	2026-05-19 17:56:54.022434+00	admin	Admin	assignedTo	admin	\N	46
111	2026-05-19 17:57:07.254691+00	admin	Admin	dueDate	2026-06-03T17:56:00Z	null	46
112	2026-05-19 17:57:27.667177+00	admin	Admin	assignedTo	admin	\N	47
113	2026-05-19 17:57:45.864364+00	admin	Admin	assignedTo	admin	mngo	22
114	2026-05-19 17:57:47.552515+00	admin	Admin	status	DONE	IN_PROGRESS	22
115	2026-05-19 19:51:01.391876+00	admin	Admin	task	Task created	Null	51
116	2026-05-19 19:51:52.43972+00	admin	Admin	task	Task created	Null	52
117	2026-05-19 21:51:22.927835+00	admin	Admin	title	Deploy app on K8s 	Deploy app lên K8s 	52
118	2026-05-19 21:51:35.667859+00	admin	Admin	status	DONE	IN_PROGRESS	7
119	2026-05-20 11:55:05.139781+00	admin	Admin	status	IN_PROGRESS	TODO	8
120	2026-05-20 11:55:08.075834+00	admin	Admin	assignedTo	admin		8
121	2026-05-21 10:29:24.211968+00	admin	Admin	status	IN_PROGRESS	TODO	51
122	2026-05-21 10:29:35.854461+00	admin	Admin	status	DONE	IN_PROGRESS	15
123	2026-05-21 10:33:42.060065+00	admin	Admin	task	Task created	Null	53
124	2026-05-22 08:20:29.90032+00	admin	Admin	status	DONE	TODO	19
125	2026-05-22 08:20:36.089148+00	admin	Admin	status	DONE	TODO	17
126	2026-05-22 12:16:24.822034+00	admin	Admin	task	Task created	Null	54
127	2026-05-22 12:16:28.229404+00	admin	Admin	status	IN_PROGRESS	TODO	54
128	2026-05-22 12:16:58.824973+00	admin	Admin	task	Task created	Null	55
129	2026-05-22 12:17:00.609527+00	admin	Admin	status	IN_PROGRESS	TODO	55
130	2026-05-22 12:17:23.911089+00	admin	Admin	status	DONE	IN_PROGRESS	14
131	2026-05-22 12:22:16.142503+00	admin	Admin	status	DONE	TODO	53
132	2026-05-24 08:50:26.08182+00	admin	Admin	status	DONE	TODO	50
133	2026-05-26 08:09:44.742566+00	admin	Admin	task	Task created	Null	56
134	2026-05-26 08:12:40.656836+00	admin	Admin	task	Task created	Null	57
135	2026-05-26 08:12:51.525352+00	admin	Admin	status	DONE	TODO	49
136	2026-05-26 08:14:54.672422+00	admin	Admin	task	Task created	Null	58
137	2026-05-26 08:14:56.920011+00	admin	Admin	status	IN_PROGRESS	TODO	58
138	2026-05-26 10:25:04.4552+00	admin	Admin	title	Integrate Keycloak	Intergate Keycloak	8
139	2026-05-26 11:45:24.634428+00	admin	Admin	status	DONE	IN_PROGRESS	58
140	2026-05-29 05:09:37.55318+00	admin	Admin	status	DONE	IN_PROGRESS	54
141	2026-05-29 05:09:42.103479+00	admin	Admin	status	DONE	IN_PROGRESS	55
142	2026-05-29 08:28:34.011691+00	admin	Admin	task	Task created	Null	59
143	2026-05-29 08:28:41.948445+00	admin	Admin	dueDate	2026-06-29T08:28:00Z	null	59
144	2026-05-29 08:28:44.434434+00	admin	Admin	dueDate	2026-06-13T08:28:00Z	2026-06-29T08:28:00Z	59
145	2026-05-29 08:30:37.219802+00	admin	Admin	task	Task created	Null	60
146	2026-06-03 11:13:50.169327+00	admin	Admin	status	DONE	TODO	57
147	2026-06-03 11:13:59.494343+00	admin	Admin	status	IN_PROGRESS	TODO	59
148	2026-06-03 11:17:06.47449+00	admin	Admin	task	Task created	Null	61
149	2026-06-03 11:17:09.467389+00	admin	Admin	status	IN_PROGRESS	TODO	61
150	2026-06-08 10:13:03.43946+00	admin	Admin	task	Task created	Null	62
151	2026-06-08 10:13:12.102657+00	admin	Admin	task	Task created	Null	63
152	2026-06-08 10:13:28.937961+00	admin	Admin	tags	aws,cloud		62
153	2026-06-08 10:13:36.006909+00	admin	Admin	assignedTo	admin	\N	62
154	2026-06-08 10:14:01.260726+00	admin	Admin	task	Task created	Null	64
155	2026-06-08 10:14:04.963293+00	admin	Admin	status	IN_PROGRESS	TODO	64
156	2026-06-08 10:15:07.967456+00	admin	Admin	task	Task created	Null	65
157	2026-06-08 10:15:10.791181+00	admin	Admin	status	IN_PROGRESS	TODO	65
158	2026-06-08 10:15:36.276549+00	admin	Admin	status	DONE	IN_PROGRESS	61
159	2026-06-08 10:15:43.433778+00	admin	Admin	status	DONE	IN_PROGRESS	48
160	2026-06-08 10:32:12.040356+00	admin	Admin	title	SAA-C03 - AWS Certified Solutions Architect - Associate - English (ENU)	AWS - SAA - Certificate	65
161	2026-06-08 10:32:53.874759+00	admin	Admin	status	DONE	IN_PROGRESS	51
162	2026-06-10 12:37:56.554706+00	admin	Admin	task	Task created	Null	66
163	2026-06-10 12:39:19.702468+00	admin	Admin	tags	aws,cloud		66
166	2026-06-11 22:45:38.434669+00	admin	Admin	task	Task created	Null	69
167	2026-06-11 22:46:00.699122+00	admin	Admin	assignedTo	admin	\N	69
168	2026-06-11 22:46:22.428604+00	admin	Admin	description	Activity group\nNotification group		69
\.


--
-- Data for Name: task_tags; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.task_tags (task_id, tag) FROM stdin;
2	frontend
3	deployment
3	vps
6	nginx
6	vps
6	linux
9	backend
9	paginator
11	sport
11	pickleball
11	drop
11	dink
16	backend
16	paginator
16	frontend
21	logger
23	assignee
24	angular material
26	dashboard
26	backend
26	tags
33	backend
33	chartjs
33	frontend
4	chartjs
4	dashboard
41	backend
36	database
41	api
41	testing
31	paginator
31	comment
31	frontend
29	autocomplete
29	frontend
30	paginator
30	comment
30	frontend
30	backend
20	dropdown
20	assignee
44	backend
44	database
44	api
40	frontend
32	tag
32	angualar material
32	frontend
25	tag
25	angular material
1	backend
1	spring boot
27	backend
27	history
18	jwt
18	token
5	priority
5	angular
5	frontend
43	logger
43	backend
42	backend
42	logger
39	search
39	backend
39	api
39	angular material
45	testing
45	frontend
37	documentation
37	postgresql
34	backend
34	testing
38	testing
38	selenium
12	sport
12	tennis
35	frontend
35	testing
28	backend
28	attachment
28	frontend
22	logger context
22	logger
52	devop
52	cloud
7	postgresql
7	database
7	linux
15	backend
15	frontend
19	assignee
19	api
17	jwt
17	token
14	kanban
14	drag & drop
8	keycloak
8	oidc
58	docker
58	cicd
60	cloud
60	aws
60	kubernetes
59	cloud
59	aws
62	aws
62	cloud
64	aws
64	cloud
65	aws
65	cloud
51	cloud
51	aws
51	devop
66	aws
66	cloud
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.users (id, fullname, password, role, username) FROM stdin;
1	Admin	abcd1234	ADMIN	admin
2	User	abcd1234	USER	user
3	Minh Ngo	abcd1234	ADMIN	mngo
4	Mia Ngo	abcd1234	USER	mia
5	Lucas Ngo	abcd1234	USER	lucas
\.


--
-- Name: activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.activity_id_seq', 4, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.notification_id_seq', 1, true);


--
-- Name: task_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.task_comment_id_seq', 109, true);


--
-- Name: task_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.task_history_id_seq', 168, true);


--
-- Name: task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.task_id_seq', 69, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: activity activity_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: task_comment task_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.task_comment
    ADD CONSTRAINT task_comment_pkey PRIMARY KEY (id);


--
-- Name: task_history task_history_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.task_history
    ADD CONSTRAINT task_history_pkey PRIMARY KEY (id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: task_tags fk5jrufop0gtxfeybb27jkoqn9r; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.task_tags
    ADD CONSTRAINT fk5jrufop0gtxfeybb27jkoqn9r FOREIGN KEY (task_id) REFERENCES public.task(id);


--
-- Name: task_comment fkpoxt1sd4otmq9p94rp1atkgs7; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.task_comment
    ADD CONSTRAINT fkpoxt1sd4otmq9p94rp1atkgs7 FOREIGN KEY (task_id) REFERENCES public.task(id);


--
-- PostgreSQL database dump complete
--

\unrestrict rVwpHfoUyzjwcFK91L0YD41RCOLn3jbUuTCRrZ5gRO8kHYM7Br13eoTT2k5a9Tx

