-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '190ac682d00d4f42' HASH 'fd18d64a2c602f78212ee2e04880bb6176764d7d14ab7cc9d90c1b28ec1d31f3' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."TASK"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 31) NOT NULL,
    "ASSIGNED_TO" CHARACTER VARYING(255),
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "DESCRIPTION" CHARACTER VARYING(255),
    "PRIORITY" ENUM('CRITICAL', 'HIGH', 'LOW', 'MEDIUM') NOT NULL,
    "STATUS" ENUM('DONE', 'IN_PROGRESS', 'TODO'),
    "TITLE" CHARACTER VARYING(255),
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE
);             
ALTER TABLE "PUBLIC"."TASK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 30 +/- SELECT COUNT(*) FROM PUBLIC.TASK;   
INSERT INTO "PUBLIC"."TASK" VALUES
(1, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-20 11:02:25+02', ' Implementing a REST API endpoint to retrieve user/task data in JSON format', 'CRITICAL', 'DONE', 'Build Backend', TIMESTAMP WITH TIME ZONE '2026-04-20 11:02:25+02'),
(2, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-20 11:02:20+02', 'Building a search bar component with Angular, including styling and autocomplete functionality', 'CRITICAL', 'DONE', 'Build Frontend', TIMESTAMP WITH TIME ZONE '2026-04-20 11:02:20+02'),
(3, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-20 11:00:25+02', 'Configure nginx and deploy the frontend and backend in a VPS', 'HIGH', 'DONE', 'Deployment on VPS', TIMESTAMP WITH TIME ZONE '2026-04-20 11:00:25+02'),
(4, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-20 11:01:25+02', 'Dashboard with number of DONE/TODO/IN_PROGRESS and chart. Using chart.js', 'HIGH', 'TODO', 'Dashboard', TIMESTAMP WITH TIME ZONE '2026-04-20 11:01:25+02'),
(5, 'lucas', TIMESTAMP WITH TIME ZONE '2026-04-20 09:00:25+02', 'Extend Task with Priority (Critial, high, medim, low) including backend and front end side.', 'HIGH', 'TODO', 'Priority Function', TIMESTAMP WITH TIME ZONE '2026-04-20 09:00:25+02'),
(6, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-19 11:00:25+02', 'Write Dockerfile and docker-compose files to enable deployment with one command', 'MEDIUM', 'DONE', 'DevOps/Configuration', TIMESTAMP WITH TIME ZONE '2026-04-19 11:00:25+02'),
(7, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-20 11:05:25+02', 'Modifying a database schema by adding a deleted_at column for soft-delete functionality', 'HIGH', 'IN_PROGRESS', 'Database Management', TIMESTAMP WITH TIME ZONE '2026-04-20 11:05:25+02'),
(8, '', TIMESTAMP WITH TIME ZONE '2026-04-20 11:10:25+02', 'Implement and integrate ODIC authentication with Keycloak', 'MEDIUM', 'TODO', 'Intergate Keycloak', TIMESTAMP WITH TIME ZONE '2026-04-20 11:10:25+02'),
(9, 'user', TIMESTAMP WITH TIME ZONE '2026-04-18 11:01:25+02', 'Backend: GET /tasks?page=0&size=10. Frontend: next / prev', 'MEDIUM', 'DONE', 'Paginator', TIMESTAMP WITH TIME ZONE '2026-04-18 11:01:25+02'),
(10, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-20 11:04:25+02', 'Add due date to task and highlight', 'HIGH', 'IN_PROGRESS', 'Due Date and Overdue', TIMESTAMP WITH TIME ZONE '2026-04-20 11:04:25+02'),
(11, 'lucas', TIMESTAMP WITH TIME ZONE '2026-04-20 11:06:25+02', 'Practice Dink and drop ', 'LOW', 'DONE', 'Play pickleball', TIMESTAMP WITH TIME ZONE '2026-04-20 11:06:25+02'),
(12, 'lucas', TIMESTAMP WITH TIME ZONE '2026-04-20 10:00:25+02', 'Play tennis today. Practice forehand', 'MEDIUM', 'TODO', 'Play Tennis', TIMESTAMP WITH TIME ZONE '2026-04-20 10:00:25+02'),
(13, 'lucas', TIMESTAMP WITH TIME ZONE '2026-04-20 08:00:25+02', 'If task is assigned. An email to assignee will be sent', 'HIGH', 'TODO', 'Email notification', TIMESTAMP WITH TIME ZONE '2026-04-20 08:00:25+02'),
(14, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-19 11:09:25+02', U&'TODO \2192 IN_PROGRESS \2192 DONE. Angular CDK Dragdrop', 'CRITICAL', 'IN_PROGRESS', 'Kanban Drag & Drop Feature', TIMESTAMP WITH TIME ZONE '2026-04-19 11:09:25+02'),
(15, 'lucas', TIMESTAMP WITH TIME ZONE '2026-04-20 11:02:50+02', 'Implement feature "Task comments"', 'LOW', 'TODO', 'Task Comments', TIMESTAMP WITH TIME ZONE '2026-04-20 11:02:50+02'),
(16, 'mia', TIMESTAMP WITH TIME ZONE '2026-04-20 12:08:00+02', 'Parse filter and sort value in url and perform sorting & filtering at server side.', 'HIGH', 'DONE', 'Deep sorting and filtering', TIMESTAMP WITH TIME ZONE '2026-04-20 12:08:00+02'),
(17, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-21 00:07:00+02', 'Extend JWT authentication with refresh token. Frontend: auto renew new token 5 minute before expiration', 'HIGH', 'TODO', 'Refresh token', TIMESTAMP WITH TIME ZONE '2026-04-21 00:07:00+02'),
(18, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-21 00:07:00+02', 'Login function with Jwt', 'HIGH', 'TODO', 'Login with Jwt', TIMESTAMP WITH TIME ZONE '2026-04-21 00:07:00+02'),
(19, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-21 01:08:00+02', 'New API to fetch all assignee list from database', 'CRITICAL', 'TODO', 'Option/ Assignee List api', TIMESTAMP WITH TIME ZONE '2026-04-21 01:08:00+02');       
INSERT INTO "PUBLIC"."TASK" VALUES
(20, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-21 02:09:00+02', 'Update frontend page Task list to use dropdown for assignee field', 'MEDIUM', 'TODO', 'Task List - Assignee Dropdown', TIMESTAMP WITH TIME ZONE '2026-04-21 02:09:00+02'),
(21, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-21 16:09:00+02', 'Singleton Logger object with levels: log, info, debug, warn and error', 'CRITICAL', 'DONE', 'Logger Service', TIMESTAMP WITH TIME ZONE '2026-04-21 16:09:00+02'),
(22, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-21 16:09:00+02', 'Extend logger service with context. The context can be set from other services', 'CRITICAL', 'IN_PROGRESS', 'Logger Service Context', TIMESTAMP WITH TIME ZONE '2026-04-21 16:09:00+02'),
(23, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-21 16:09:00+02', 'Show assigned to me tasks in dashboard', 'CRITICAL', 'DONE', 'Assigned to Me', TIMESTAMP WITH TIME ZONE '2026-04-21 16:09:00+02'),
(24, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-21 16:10:00+02', 'New Angular component for task details', 'MEDIUM', 'DONE', 'Task Details component', TIMESTAMP WITH TIME ZONE '2026-04-21 16:10:00+02'),
(25, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-21 23:10:00+02', 'Each task can have multiple tags', 'LOW', 'TODO', 'Tags feature', TIMESTAMP WITH TIME ZONE '2026-04-21 23:10:00+02'),
(26, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:10:00+02', 'Top tags in dashboard', 'CRITICAL', 'DONE', 'Top Tags', TIMESTAMP WITH TIME ZONE '2026-04-22 23:10:00+02'),
(27, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'Task history feature for auditing', 'LOW', 'TODO', 'Task Historiy', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02'),
(28, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-23 08:10:00+02', 'Task can have multiple attachments', 'HIGH', 'IN_PROGRESS', 'File Upload', TIMESTAMP WITH TIME ZONE '2026-04-22 08:10:00+02'),
(29, 'mngo', TIMESTAMP WITH TIME ZONE '2026-04-23 08:10:00+02', 'by entering tag, the suggestion box mus tbe appeared', 'HIGH', 'TODO', 'Tag autocomplete', TIMESTAMP WITH TIME ZONE '2026-04-22 08:10:00+02'),
(30, 'admin', TIMESTAMP WITH TIME ZONE '2026-04-23 12:10:00+02', 'Paginator for comment section and with load more buttons', 'HIGH', 'TODO', 'Comment paginator', TIMESTAMP WITH TIME ZONE '2026-04-23 12:10:00+02'); 
CREATE CACHED TABLE "PUBLIC"."TASK_TAGS"(
    "TASK_ID" BIGINT NOT NULL,
    "TAG" CHARACTER VARYING(255)
);               
-- 60 +/- SELECT COUNT(*) FROM PUBLIC.TASK_TAGS;              
INSERT INTO "PUBLIC"."TASK_TAGS" VALUES
(1, 'backend'),
(1, 'spring boot'),
(2, 'frontend'),
(3, 'deployment'),
(3, 'vps'),
(4, 'chartjs'),
(4, 'dashboard'),
(5, 'priority'),
(5, 'angular'),
(5, 'frontend'),
(6, 'nginx'),
(6, 'vps'),
(6, 'linux'),
(7, 'postgresql'),
(7, 'database'),
(8, 'keycloak'),
(8, 'oidc'),
(9, 'backend'),
(9, 'paginator'),
(11, 'sport'),
(11, 'pickleball'),
(11, 'drop'),
(11, 'dink'),
(12, 'sport'),
(12, 'tennis'),
(14, 'kanban'),
(14, 'drag & drop'),
(15, 'backend'),
(15, 'frontend'),
(16, 'backend'),
(16, 'paginator'),
(16, 'frontend'),
(17, 'jwt'),
(17, 'token'),
(18, 'jwt'),
(18, 'token'),
(19, 'assignee'),
(19, 'api'),
(20, 'dropdown'),
(20, 'assignee'),
(21, 'logger'),
(22, 'logger context'),
(22, 'logger'),
(23, 'assignee'),
(24, 'angular material'),
(25, 'tag'),
(25, 'angular material'),
(26, 'dashboard'),
(26, 'backend'),
(26, 'tags'),
(27, 'backend'),
(27, 'history'),
(28, 'backend'),
(28, 'attachment'),
(28, 'frontend'),
(29, 'autocomplete'),
(29, 'frontend'),
(30, 'paginator'),
(30, 'comment'),
(30, 'frontend');            
CREATE CACHED TABLE "PUBLIC"."TASK_COMMENT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 40) NOT NULL,
    "CONTENT" CHARACTER VARYING(255),
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "CREATED_BY" CHARACTER VARYING(255),
    "CREATED_BY_FULL_NAME" CHARACTER VARYING(255),
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "TASK_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."TASK_COMMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID"); 
-- 39 +/- SELECT COUNT(*) FROM PUBLIC.TASK_COMMENT;           
INSERT INTO "PUBLIC"."TASK_COMMENT" VALUES
(1, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 25),
(2, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 25),
(3, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 25),
(4, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 25),
(5, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 25),
(6, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 25),
(7, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 26),
(8, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 26),
(9, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 26),
(10, 'Nice feature, very useful for analytics!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 26),
(11, 'Maybe we should add pagination for tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 26),
(12, U&'UI looks clean \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 26),
(13, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 27),
(14, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 27),
(15, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 27),
(16, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 28),
(17, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 28),
(18, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 28),
(19, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 29),
(20, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 29),
(21, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 29),
(22, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-23 12:15:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 30),
(23, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-23 12:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 30),
(24, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-23 12:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 30);    
INSERT INTO "PUBLIC"."TASK_COMMENT" VALUES
(25, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-23 12:30:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 30),
(26, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-23 12:35:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 30),
(27, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-23 12:36:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 30),
(28, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-23 12:37:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 30),
(29, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-23 12:38:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 30),
(30, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-23 12:39:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 30),
(31, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-23 12:40:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 30),
(32, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-23 12:41:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 30),
(33, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-23 12:42:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 30),
(34, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-23 12:43:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 30),
(35, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-23 12:44:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 30),
(36, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-23 12:45:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 30),
(37, 'Nice feature, very useful for searching!', TIMESTAMP WITH TIME ZONE '2026-04-23 12:46:00+02', 'admin', 'Admin', TIMESTAMP WITH TIME ZONE '2026-04-22 23:15:00+02', 30),
(38, 'Maybe we should have search fucntion by multiple tags?', TIMESTAMP WITH TIME ZONE '2026-04-23 12:20:00+02', 'mngo', 'Minh Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:20:00+02', 30),
(39, U&'UI looks greate \+01f44d', TIMESTAMP WITH TIME ZONE '2026-04-23 12:25:00+02', 'lucas', 'Lucas Ngo', TIMESTAMP WITH TIME ZONE '2026-04-22 23:25:00+02', 30);     
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "FULLNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "ROLE" ENUM('ADMIN', 'USER'),
    "USERNAME" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'Admin', 'abcd1234', 'ADMIN', 'admin'),
(2, 'User', 'abcd1234', 'USER', 'user'),
(3, 'Minh Ngo', 'abcd1234', 'ADMIN', 'mngo'),
(4, 'Mia Ngo', 'abcd1234', 'USER', 'mia'),
(5, 'Lucas Ngo', 'abcd1234', 'USER', 'lucas');         
ALTER TABLE "PUBLIC"."TASK_TAGS" ADD CONSTRAINT "PUBLIC"."FK5JRUFOP0GTXFEYBB27JKOQN9R" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."TASK_COMMENT" ADD CONSTRAINT "PUBLIC"."FKPOXT1SD4OTMQ9P94RP1ATKGS7" FOREIGN KEY("TASK_ID") REFERENCES "PUBLIC"."TASK"("ID") NOCHECK;    
