spring.application.name=TaskTracker

# H2 Database URL
spring.datasource.url=jdbc:h2:file:./data/taskdb
# Driver H2
spring.datasource.driverClassName=org.h2.Driver
# Mặc định của H2
spring.datasource.username=sa
spring.datasource.password=
# Dialect cho JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.show-sql=true
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.sql.init.mode=always

# Cho phép H2 Console để xem dữ liệu trên trình duyệt
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true

# Tự động tạo bảng từ Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true


