spring.application.name=TaskTracker

# H2 Database URL
#spring.datasource.url=jdbc:h2:file:./data/taskdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Cho phép H2 Console để xem dữ liệu trên trình duyệt
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Postgresql1234!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.jpa.show-sql=true
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Tự động tạo bảng từ Entity
spring.jpa.hibernate.ddl-auto=update

# data source initialization
#spring.sql.init.mode=never
#spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


