name: CI/CD TaskTracker

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 🧱 Build Backend
      - name: Build Backend
        working-directory: TaskTracker
        run: |
          chmod +x mvnw
          #./mvnw clean package -DskipTests
          ./mvnw clean package
      
       # 📦 Install FE deps (CHỈ 1 LẦN)
      - name: Install Frontend deps
        working-directory: TaskTrackerFrontend
        run: npm ci
        
      - name: Test Frontend (Unit - Vitest)
        working-directory: TaskTrackerFrontend
        run: npm run test -- --watch=false
        
      # 🌐 Build Frontend before E2E test
      - name: Build Frontend
        working-directory: TaskTrackerFrontend
        run: npm run build -- --configuration production

       # ⚡ Cache Playwright (Important to improve performance)
      #- name: Cache Playwright browsers
      #  uses: actions/cache@v3
      #  with:
      #   path: ~/.cache/ms-playwright
      #    key: ${{ runner.os }}-playwright

      #- name: Install Playwright Browsers
      #  working-directory: TaskTrackerFrontend
      #  run: npx playwright install --with-deps

      #- name: Playwright E2E Tests
      #  working-directory: TaskTrackerFrontend
      #  run: npx playwright test
    


      # 🔐 Docker login
      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🐳 Backend image
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tasktracker-backend ./TaskTracker
          docker push ${{ secrets.DOCKER_USERNAME }}/tasktracker-backend

      # 🐳 Frontend image
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tasktracker-frontend ./TaskTrackerFrontend
          docker push ${{ secrets.DOCKER_USERNAME }}/tasktracker-frontend

      # 🚀 Deploy
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/tasktracker
            docker pull ${{ secrets.DOCKER_USERNAME }}/tasktracker-backend
            docker pull ${{ secrets.DOCKER_USERNAME }}/tasktracker-frontend
            docker-compose down
            docker-compose up -d